### ISSUE TITLE
Add ingress integration support

### ISSUE THREAD

**Issue by GerDner** [canonical/vault-operator#256]
### Enhancement Proposal

Coming from charmed-kubernetes, one would like to replace the default vault overlay with the most recent vault-charm version 1.15 https://github.com/charmed-kubernetes/bundle/blob/main/overlays/vault-pki-overlay.yaml
and expect similar features as in  v1.8 of the charm not aware, that we are talking about totally different Charms.
Motivation could be, that 1.15 supports S3 Backups for example.

This will break the Vault integration because the certificates relation will not work out of the box anymore.

So I propose multiple enhancements as this can be solved in different ways:

1. Add Docs or a hint that there are differences between in 1.8 and 1.15 feature wise and configuration wise. 
3. Add the Feature for Vault acting as a Root-CA because it's a valid use-case 
4. Change logging from debug to warning in https://github.com/canonical/vault-operator/blob/main/src/charm.py#L1041 
    Currently it's difficult to understand why the certificates relation is never coming up.

**Comment by gruyaume** [comment]
Hello @GerDner, thank you for reaching out. These are somewhat independent enhancements requests. In the future I would encourage to operate separate GitHub issues for those as it's possible we address one and not the other.

## 1. Add Docs or a hint that there are differences between in 1.8 and 1.15 feature wise and configuration wise.

The Vault charm for 1.15 is brand new and there is no guarantees related with upgrading from 1.8. I agree that we should document this.

##  2. Add the Feature for Vault acting as a Root-CA because it's a valid use-case

You can use Vault as an intermediate CA right now. Depending on your use case, its parent CA can be [Self Signed Certificates](https://charmhub.io/self-signed-certificates), or [Manual TLS Certificates](https://charmhub.io/manual-tls-certificates).  We would need to understand your use case a bit better to commit to changing this.

## 3. Change logging from debug to warning

I think it's fine for this log to be in debug. Warning  are conditions that prevent an application from functioning as it should. Deployments that do not rely on this PKI integration should not be seeing a warning related to this relation not being created. The vault charm should function perfectly fine without this integration.

**Comment by GerDner** [comment]
Hello @gruyaume

got it, i'll split it next time. 

1. I try to come up with a Proposal then. But if i got the Docs Guide correctly i'm missing Level 3 on https://discourse.charmhub.io/ to contribute to docs.
2. Use-Case is: Replace vault 1.8 in charmed-kubernetes bundle (vault-overlay -> see https://charmhub.io/vault/docs/h-use-vault-as-intermediate-ca?channel=1.15/stable) with 1.15 to get all the new features like s3 Backup.
So I was kind of expecting something like "generate-root-ca" action from 1.8 which does not require a new Container/VM like. [Self Signed Certificates](https://charmhub.io/self-signed-certificates) does. Does this make sense?
As an alternative, we could extend docs to address this use case (coming from charmed-kubernetes) and point the user to self-signed-certifcated.
3. Comin from charmed-kubernetes bundle, I was kind of lost because I expected things to work similar.
In my opinion, the vault-pki relation should complain about missing relations/config if a charm requests certificates, but the vault charm cannot fulfill the request since a root-ca is missing. 

> Deployments that do not rely on this PKI integration should not be seeing a warning related to this relation not being created.

This Code is only executed then a vault-pki relation is integrated, no? So Deployments not relying on PKI should not see it. But so does deployments which rely on the PKI. They fail silently? At least this was my observation.
Correct me if I'm wrong. I'm new to charms and just getting started :)

**Comment by GerDner** [comment]
Hi @saltiyazan 
It helped me a little - thanks!

But i think there are still missing parts. 
I can't get it to work with existing charms like etcd or charmed kubernetes and I think it's because there are more missing features in 1.15.

**Comment by GerDner** [comment]
@saltiyazan Vault 1.8 had KV Secret Engine Support. 
Any reason why you wrote "Support the key value secrets engine"? 

See: https://charmhub.io/vault/integrations#secrets which defines the same interface as in vault 1.15

**Comment by saltiyazan** [comment]
> @saltiyazan Vault 1.8 had KV Secret Engine Support. Any reason why you wrote "Support the key value secrets engine"?
> 
> See: https://charmhub.io/vault/integrations#secrets which defines the same interface as in vault 1.15

Thanks for pointing this out, that seems wrong, I'll fix it.

**Comment by GerDner** [comment]
Cool! Thanks for the Update.

May we add information about what is currently not supported anymore? (I'm unsure about which side should contain this info - it also could make sense that the requiring side addresses this?)

What comes into mind is: 
1. Multiple Domains are not supported anymore in PKI
2. Vault UI is now supported (was not in 1.8)
3. Loadbalancing Vault via loadbalancer integration is not Supported anymore (Use-Case: one would need one single IP/DNS for external Auth via oidc -> redirect_url)
4. Defining a snap channel for the vault snap is not supported anymore
5. In general (maybe you need to confirm this): v0 of the tls_certificates is not supported anymore?

So it seems that charms currently integration with vault were supported in 1.8 and are not supported anymore.
So what is the case: does charmed-kubernetes not support vault 1.15 or does vault 1.15 not support charmed-kubernetes anymore?

Example: charmed-kubernetes

The bundles define a vault-overlay.yaml for vault integration. One could increase the channel to 1.15/stable and believe things to work. This may be addressed in charmed-kubernetes since this is the side mentioning the vault integration.

**Comment by saltiyazan** [comment]
> * Loadbalancing Vault via loadbalancer integration is not Supported anymore (Use-Case: one would need one single IP/DNS for external Auth via oidc -> redirect_url)

Awesome, thanks a lot for the feedback, it's really helpful. I have added these points.

For .3 could you please create an issue? or provide more information here? I'd be interested in understanding the use case, maybe the integration is required and maybe a different integration can be used.

**Comment by GerDner** [comment]
Comparable to https://charmhub.io/vault-k8s/integrations#ingress but for machine deployments

**Comment by saltiyazan** [comment]
Thanks for the detailed explanation @GerDner , I created a ticket in our backlog to tackle this.

**Comment by gruyaume** [comment]
The addition of the `ingress` integration will be done part of the 25.04 sprint. Here we will make it possible to integrate Vault with [HA Proxy](https://github.com/canonical/haproxy-operator).
